version: "3"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "14333:1433"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    command: --config /etc/grafana/grafana.ini

  fluxo-de-caixa:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sql-server
      - prometheus
      - grafana
